architecture: YOLOv5
# pretrain_weights: "weights/yolov5s.pdparams"
pretrain_weights: ""
# weights: "output/yolov5s_coco/model_final"
norm_type: bn

YOLOv5:
  backbone: CSPDarknet
  neck: YOLOv5FPN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

CSPDarknet:
  depth_multiple: 0.33
  width_multiple: 0.50

YOLOv5FPN:
  depth_multiple: 0.33
  width_multiple: 0.50
  feature_maps: [17, 20, 23]

YOLOv3Head:
  anchors:
    [
      [10, 13],
      [16, 30],
      [33, 23],
      [30, 61],
      [62, 45],
      [59, 119],
      [116, 90],
      [156, 198],
      [373, 326],
    ]
  anchor_masks: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
  loss: YOLOv5Loss

YOLOv5Loss:
  downsample: [8, 16, 32]

BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.005
    downsample_ratio: 32
    clip_bbox: true
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.01
    nms_threshold: 0.45
    nms_top_k: 1000

